### ISSUE TITLE
c3p0 throws exceptions on RAW files (NEF)

### ISSUE THREAD

**Issue by botic** [peshkira/c3po#1]
FITS returned "300 300 300" for "xSamplingFrequency" on a Nikon NEF RAW-file, which c3po tries to save as float. Normally the value is only an integer for JPEG, but i think for RAW this metadata entry is saved for every RGB color channel separately. This leads to an exception:

11:18:18,153 WARN  [FloatValue] The passed string '300 300 300' is not a valid float. Setting value to null.
11:18:18,159 WARN  [IntegerValue] The passed string '3 1 1' is not a valid integer. Setting value to null.
11:18:18,318 ERROR [LocalTransactionalDAO] c3po caught an error: Validation failed for classes [com.petpet.c3po.datamodel.FloatValue] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
    ConstraintViolationImpl{interpolatedMessage='kann nicht null sein', propertyPath=fValue, rootBeanClass=class com.petpet.c3po.datamodel.FloatValue, messageTemplate='{javax.validation.constraints.NotNull.message}'}
]
11:18:18,365 WARN  [JDBCExceptionReporter] SQL Error: 0, SQLState: null
11:18:18,365 ERROR [JDBCExceptionReporter] Batch-Eintrag 0 insert into Value (element_id, measuredAt, property_id, reliability, source_id, status, value, id) values (118818, 0, 10, 0, 2, CONFLICT, 6.0, 3276800) wurde abgebrochen.  Rufen Sie 'getNextException' auf, um die Ursache zu erfahren.
11:18:18,366 WARN  [JDBCExceptionReporter] SQL Error: 0, SQLState: 23503
11:18:18,366 ERROR [JDBCExceptionReporter] ERROR: insert or update on table "value" violates foreign key constraint "fk4e9a151b474df4d"
  Detail: Key (element_id)=(118818) is not present in table "element".
11:18:18,366 ERROR [LocalTransactionalDAO] c3po caught an error: org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update, object /Users/philipp/Pictures/Photo-Library/2011/06_Donauinselfest/DSC_3666.NEF could not be persisted
11:18:18,366 WARN  [LocalTransactionalDAO] Transaction is still active, rolling it back manually
11:18:18,368 INFO  [LocalTransactionalDAO] Flushing session

Here a file generated by FITS:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;fits xmlns=&quot;http://hul.harvard.edu/ois/xml/ns/fits/fits_output&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd&quot; version=&quot;0.6.0&quot; timestamp=&quot;22.04.12 16:05&quot;&gt;
  &lt;identification status=&quot;CONFLICT&quot;&gt;
    &lt;identity format=&quot;Tagged Image File Format&quot; mimetype=&quot;image/tiff&quot; toolname=&quot;FITS&quot; toolversion=&quot;0.6.0&quot;&gt;
      &lt;tool toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; /&gt;
      &lt;tool toolname=&quot;file utility&quot; toolversion=&quot;5.03&quot; /&gt;
      &lt;tool toolname=&quot;Droid&quot; toolversion=&quot;3.0&quot; /&gt;
      &lt;tool toolname=&quot;NLNZ Metadata Extractor&quot; toolversion=&quot;3.4GA&quot; /&gt;
      &lt;tool toolname=&quot;ffident&quot; toolversion=&quot;0.2&quot; /&gt;
      &lt;version toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;CONFLICT&quot;&gt;6.0&lt;/version&gt;
      &lt;version toolname=&quot;Droid&quot; toolversion=&quot;3.0&quot; status=&quot;CONFLICT&quot;&gt;3&lt;/version&gt;
      &lt;version toolname=&quot;Droid&quot; toolversion=&quot;3.0&quot; status=&quot;CONFLICT&quot;&gt;4&lt;/version&gt;
      &lt;version toolname=&quot;Droid&quot; toolversion=&quot;3.0&quot; status=&quot;CONFLICT&quot;&gt;5&lt;/version&gt;
      &lt;externalIdentifier toolname=&quot;Droid&quot; toolversion=&quot;3.0&quot; type=&quot;puid&quot;&gt;fmt/7&lt;/externalIdentifier&gt;
      &lt;externalIdentifier toolname=&quot;Droid&quot; toolversion=&quot;3.0&quot; type=&quot;puid&quot;&gt;fmt/8&lt;/externalIdentifier&gt;
      &lt;externalIdentifier toolname=&quot;Droid&quot; toolversion=&quot;3.0&quot; type=&quot;puid&quot;&gt;fmt/9&lt;/externalIdentifier&gt;
      &lt;externalIdentifier toolname=&quot;Droid&quot; toolversion=&quot;3.0&quot; type=&quot;puid&quot;&gt;fmt/10&lt;/externalIdentifier&gt;
    &lt;/identity&gt;
    &lt;identity format=&quot;NEF EXIF&quot; mimetype=&quot;image/x-raw&quot; toolname=&quot;FITS&quot; toolversion=&quot;0.6.0&quot;&gt;
      &lt;tool toolname=&quot;Exiftool&quot; toolversion=&quot;7.74&quot; /&gt;
    &lt;/identity&gt;
  &lt;/identification&gt;
  &lt;fileinfo&gt;
    &lt;size toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot;&gt;12842376&lt;/size&gt;
    &lt;creatingApplicationName toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot;&gt;Ver.1.02&lt;/creatingApplicationName&gt;
    &lt;lastmodified toolname=&quot;Exiftool&quot; toolversion=&quot;7.74&quot; status=&quot;SINGLE_RESULT&quot;&gt;2011:06:25 14:22:56+02:00&lt;/lastmodified&gt;
    &lt;created toolname=&quot;Exiftool&quot; toolversion=&quot;7.74&quot; status=&quot;SINGLE_RESULT&quot;&gt;2011:06:25 14:22:57&lt;/created&gt;
    &lt;filepath toolname=&quot;OIS File Information&quot; toolversion=&quot;0.1&quot; status=&quot;SINGLE_RESULT&quot;&gt;/Users/philipp/Pictures/Photo-Library/2011/06_Donauinselfest/DSC_3667.NEF&lt;/filepath&gt;
    &lt;filename toolname=&quot;OIS File Information&quot; toolversion=&quot;0.1&quot; status=&quot;SINGLE_RESULT&quot;&gt;/Users/philipp/Pictures/Photo-Library/2011/06_Donauinselfest/DSC_3667.NEF&lt;/filename&gt;
    &lt;md5checksum toolname=&quot;OIS File Information&quot; toolversion=&quot;0.1&quot; status=&quot;SINGLE_RESULT&quot;&gt;5aa8e24a47a3bab9e763af026c9930e8&lt;/md5checksum&gt;
    &lt;fslastmodified toolname=&quot;OIS File Information&quot; toolversion=&quot;0.1&quot; status=&quot;SINGLE_RESULT&quot;&gt;1309004576000&lt;/fslastmodified&gt;
  &lt;/fileinfo&gt;
  &lt;filestatus&gt;
    &lt;well-formed toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;true&lt;/well-formed&gt;
    &lt;valid toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;false&lt;/valid&gt;
    &lt;message toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;PhotometricInterpretation not defined&lt;/message&gt;
    &lt;message toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;ImageWidth not defined&lt;/message&gt;
    &lt;message toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;ImageLength not defined&lt;/message&gt;
    &lt;message toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;Neither strips nor tiles defined&lt;/message&gt;
    &lt;message toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;JPEGProc not defined for JPEG compression&lt;/message&gt;
  &lt;/filestatus&gt;
  &lt;metadata&gt;
    &lt;image&gt;
      &lt;byteOrder toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;big endian&lt;/byteOrder&gt;
      &lt;byteOrder toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;big endian&lt;/byteOrder&gt;
      &lt;byteOrder toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;big endian&lt;/byteOrder&gt;
      &lt;compressionScheme toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;CONFLICT&quot;&gt;Uncompressed&lt;/compressionScheme&gt;
      &lt;compressionScheme toolname=&quot;NLNZ Metadata Extractor&quot; toolversion=&quot;3.4GA&quot; status=&quot;CONFLICT&quot;&gt;65536&lt;/compressionScheme&gt;
      &lt;imageWidth toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot;&gt;160&lt;/imageWidth&gt;
      &lt;imageHeight toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot;&gt;120&lt;/imageHeight&gt;
      &lt;colorSpace toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;RGB&lt;/colorSpace&gt;
      &lt;referenceBlackWhite toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;0.0 255.0 0.0 255.0 0.0 255.0&lt;/referenceBlackWhite&gt;
      &lt;YCbCrPositioning toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;Co-sited&lt;/YCbCrPositioning&gt;
      &lt;orientation toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;CONFLICT&quot;&gt;normal*&lt;/orientation&gt;
      &lt;orientation toolname=&quot;NLNZ Metadata Extractor&quot; toolversion=&quot;3.4GA&quot; status=&quot;CONFLICT&quot;&gt;65536&lt;/orientation&gt;
      &lt;samplingFrequencyUnit toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot;&gt;in.&lt;/samplingFrequencyUnit&gt;
      &lt;xSamplingFrequency toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;CONFLICT&quot;&gt;300 300 300&lt;/xSamplingFrequency&gt;
      &lt;xSamplingFrequency toolname=&quot;NLNZ Metadata Extractor&quot; toolversion=&quot;3.4GA&quot; status=&quot;CONFLICT&quot;&gt;44.00390625&lt;/xSamplingFrequency&gt;
      &lt;ySamplingFrequency toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;CONFLICT&quot;&gt;300 300 300&lt;/ySamplingFrequency&gt;
      &lt;ySamplingFrequency toolname=&quot;NLNZ Metadata Extractor&quot; toolversion=&quot;3.4GA&quot; status=&quot;CONFLICT&quot;&gt;44.00390625&lt;/ySamplingFrequency&gt;
      &lt;bitsPerSample toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot;&gt;8 8 8&lt;/bitsPerSample&gt;
      &lt;bitsPerSample toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;1&lt;/bitsPerSample&gt;
      &lt;bitsPerSample toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;12&lt;/bitsPerSample&gt;
      &lt;samplesPerPixel toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;CONFLICT&quot;&gt;3 1 1&lt;/samplesPerPixel&gt;
      &lt;samplesPerPixel toolname=&quot;NLNZ Metadata Extractor&quot; toolversion=&quot;3.4GA&quot; status=&quot;CONFLICT&quot;&gt;196608&lt;/samplesPerPixel&gt;
      &lt;imageProducer toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot; /&gt;
      &lt;scanningSoftwareName toolname=&quot;Jhove&quot; toolversion=&quot;1.5&quot; status=&quot;SINGLE_RESULT&quot;&gt;Ver.1.02&lt;/scanningSoftwareName&gt;
    &lt;/image&gt;
  &lt;/metadata&gt;
&lt;/fits&gt;

**Comment by peshkira** [comment]
Hi!

Ja das ist bekannt. C3po sollte dieser Wert dann wegnehmen oder das Element wegnehmen und weitermachen.
Hat es ihn aufgehalten? Wenn ja, dann am besten diese FITS Datei wegnehmen, aber ich glaube nicht, dass es ihn aufhalten soll.
Von der Portion des logs kann ich leider nicht sagen, ob er weiter macht oder nicht.

**Comment by botic** [comment]
c3po macht weiter. Ich hab jetzt eine Menge Lightroom-Previews in der Datenbank (JPEGs), aber keine Originaldateien (RAW/NEF).

**Comment by peshkira** [comment]
INVALID, FIXED

The issue is not valid anymore, due to the new underlying data store implementation (Mongo).
Now the parsing does not care and just stores the problematic values and  warns about the unsuccessful type conversion.
The conflicts are also correctly stored.
