### ISSUE TITLE
compile with play

### ISSUE THREAD

**Issue by gregor2005** [peshkira/c3po#36]
hi,

i have installed c3po and let it eat some xml files from fits i get a nice csv file.
now i tried to use the webinterface and therefore i downloaded play and run the command: ../../play/play-2.0.4/play clean compile stage

i get the following error, i hope that somebody can help:

....
[info] downloading http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-core-common_2.9.1/0.8/play2-war-core-common_2.9.1-0.8.jar ...
[info]  [SUCCESSFUL ] com.github.play2war#play2-war-core-common_2.9.1;0.8!play2-war-core-common_2.9.1.jar (1731ms)
[info] Done updating.
[error] {file:<path to the stored folder>/c3po/c3po/c3po-webapi/}c3po/compile:sources: java.lang.ExceptionInInitializerError
[error] Total time: 100 s, completed 11.03.2013 21:56:51

EDIT: i get the same with: ../../play/play-2.0.4/play package

**Comment by peshkira** [comment]
hi!

that is strange. Can you give me some information about the system you are running it on?

**Comment by gregor2005** [comment]
os: fedora 18 x86_64 3.8.1-201.fc18.x86_64
java: oracle 1.7.0_15
play: play-2.0.4
EDIT: maven: Apache Maven 3.0.4

**Comment by peshkira** [comment]
Could it be because of Java 7. I use 6. It should be backward compatible, but you never know if some library isn't. If it is not much of a hassle, could you try switching to 6?

**Comment by gregor2005** [comment]
i have now totally removed java 7 and installed java 6 (1.6.0_43) but i get the same exception.
which os do you use so i can install it in a vm to use c3po

**Comment by peshkira** [comment]
I develop on a mac. However, I also have a Ubuntu machine, where everything seems to work. Many of my former colleagues use windows and it seems to work for them as well.

I don't think it is the OS causing the problem, but I have no way to be absolutely sure. If you want to try something else out, it would be awesome. Please report back with the results...

**Comment by gregor2005** [comment]
i did it now with ubuntu 12.10 and i get the same error now with openjdk (1.6.0_27)
very bad because i need c3po for a lecture at the technical university of vienna for digital preservation

**Comment by luis100** [comment]
@gregor2005, I used the c3po in the link below, but had to update my openjdk to 1.7 in ubuntu 12.04:

Download https://www.dropbox.com/s/xyx780au0zxqpte/c3po-webapi.zip

```
$ sudo apt-get install openjdk-7-jdk
$ sudo update-alternatives --config java
$ sudo update-alternatives --config javac
$ sudo update-alternatives --config javaws
$ unzip c3po-webapi.zip
$ cd c3po-webapi
$ ./target/start &
```

Also, you might want to download the c3po-cmd jar, if you don't already have it:
https://www.dropbox.com/s/80vgchnexkbm8ok/c3po-cmd-0.2.0-jar-with-dependencies.jar

**Comment by peshkira** [comment]
I haven't used open jdk, so I have no idea what the problem might be. Please try what Luis suggested or install the standard Sun/Oracle JDK.

Please also, note that I am no longer affiliated to the University of Technology, so you might want to ask for support for the lecture in tuwel. Let me know, if I can help you woth anything else that is related to c3po and the problem you are having.

**Comment by gregor2005** [comment]
@luis100 THANKS YOU, with your c3po-webapi.zip i can use the webinterface.

**Comment by luis100** [comment]
Still, installation process seems hard and many people are having problems with it when starting from sources. This should be looked into.
