### ISSUE TITLE
[Core] No method to remove/update a collection

### ISSUE THREAD

**Issue by luis100** [peshkira/c3po#38]
When files are removed from a collection, there is no method on the command line tool to remove the collection before giving the new set of FITS files, or to define this new list of FITS files as the updated list (removing previous ones).

This is necessary when monitoring the content of a repository or folder, where files can be added, updated or removed.

**Comment by peshkira** [comment]
That's a good idea. I might eve do that before the next release with the outcomes of the spruce event.
