### ISSUE TITLE
[C3PO] Size'o'Matic ignores the number of samples

### ISSUE THREAD

**Issue by kraxner** [peshkira/c3po#42]
Sample selection algorithm Size'o'Matic seems to ignore the given number of samples.
(This works for the other algorithms)

**Comment by peshkira** [comment]
Are you sure. I just tried it out and it seems to work for me. How many elements do you have in the collection? How many do you choose. Also note that the number is just a limit. If there are not enough samples to be found then less will be returned.

If you can give me some hints to reproduce it, it will be great. But I will double-check!

**Comment by kraxner** [comment]
I tried it on the roda test instance, it is true, at the moment there are only 8 objects in total. 
But it always gives me two representatives, even if I choose 1 sample only. Maybe one representative alone does not make sense and therefore it delivers two?

**Comment by peshkira** [comment]
Ah ok. that is better. I can reproduce it. I beleive I have a clue what might be the problem. I will look into it when I have time. Thanks

**Comment by kraxner** [comment]
If I provide no value at all, all samples are chosen
If I choose 8 samples, also all 8 samples are chosen,
but if I provide a value below that, only 2 are chosen
