### ISSUE TITLE
[Core] An amount of Size'o'Matic samples should be 3, not 5.

### ISSUE THREAD

**Issue by artourkin** [peshkira/c3po#44]
Due to time limitations at the review, we need only 3 samples in a profile output. 5 samples is too much.

**Comment by peshkira** [comment]
Well, as discussed, you can just change the hard coded value in the ProfileGenerator and that should do it for the review. However, I don't believe it should be 3. It should be configurable by a parameter passed in the command line, or via the SamplesController in the WebApp...

**Comment by kraxner** [comment]
yes, in the end the number of samples and the algorithm should be configurable via the Sample Selection GUI in the WebApp (and maybe additionally via cmd line parameters), as described in  #43

**Comment by peshkira** [comment]
I am closing this issue as it is splitted in these two: #42, #45
