### ISSUE TITLE
64-bit database vs 32-bit database

### ISSUE THREAD

**Issue by techmaurice** [peshkira/c3po#61]
Our office environment is WinXP 32-bit, soon migrating to Win7 32-bit.

I managed to run C3PO and gather data on WinXP 32-bit with a 32-bit MongoDB install, although for one (1) collection. There is a particular collection that makes C3PO choke, will submit a separate issue for that It probably is a 64-bit vs 32-bit issue...

Question:
What is the reason for C3PO to require a 64-bit database?
- database size (max 4 GB)?
- integer lengths?

Is there any possibility that C3PO will support 32-bit natively as well, as many office environments (not only ours...) are still 32-bit because of legacy applications?

**Comment by peshkira** [comment]
Hi Maurice!

The reason for the 64bit requirement is that Mongo supports only up to 2GB of data in the 32 bit version.
This makes it rather useless for the use case scenarios of c3po. To my knowing there are no other limitations that have influence on c3po.

So to answer your question: 

> Is there any possibility that C3PO will support 32-bit natively as well, as many office environments (not only ours...) are still 32-bit because of legacy applications?

Running c3po with a 32 bit MongoDB in the backend shouldn't be a problem per se. It will just not support more data as soon as you reach the 2GB limit and will probably fail inserting. If you have other specific issues, please open them here.

If this answers your problem, please close this issue.

**Comment by techmaurice** [comment]
Hi Petar,

It might make sense to abstract the database interface. That way one could use for example MySQL, with a separate table per collection. This is useful as a table in MySQL can hold up to 2TB (!) on a Win 32-bit system with a NTFS file system.
http://dev.mysql.com/doc/refman/5.0/en/table-size-limit.html

Next to tackling the table size limit this makes it possible to run multiple instances of C3PO using a central database server.

What are your thoughts on this?

**Comment by peshkira** [comment]
The Database interface is abstracted. You can take a look here: https://github.com/peshkira/c3po/wiki/Development-Guide#how-do-i-implement-a-new-persistencelayer and if interested implement a different backend (e.g. MySQL)

The challenge is to map the `Model` objects to some meaningful RDBMS tables.
However, the very first implementation of c3po used a relational database and it wasn't as efficient, as I wanted it to be - as in some cases it required so many JOIN operations that it didn't terminate. Maybe there is a better mapping. If you try to tackle this, I will be glad to help and adapt the persistence layer interface to your needs - as long as this does not break the current implementation.

Regarding the multiple instances of c3po against a central DB:
If you talk about the command line and the import/gather meta data procedure - that is possible now as well.
The only think you have to consider is that the metadata has to be splitted in separate folders on the file system

**Comment by techmaurice** [comment]
I will look into this for MySQL and take careful consideration of all above. Closing issue as this answered my question.
