### ISSUE TITLE
Adding collection requires restart of Play deployment

### ISSUE THREAD

**Issue by techmaurice** [peshkira/c3po#66]
If a collection is added C3PO requires a restart of the Play deployment.

This is a minor issue, but it would be nice if the new collection becomes visible after a page refresh.

**Comment by peshkira** [comment]
are you sure that this is true? for me a page refresh works fine. I will investigate

**Comment by techmaurice** [comment]
Tried again and you are right, it does update. Maybe my browser cached the page. Closing issue.
